### ISSUE TITLE
Add basic auth for user authentication in addition to client certs

### ISSUE THREAD

**Issue by simoami** [coreos/kube-aws#355]
Hello, is there a guide to add basic auth for user auth to the api server? I'd like to add it as a secondary mean of accessing the dashboard ui on the browser without using a proxy.

Quoting the docs:
> You can enable multiple authentication methods at once. You should usually use at least two methods:
> - service account tokens for service accounts
> - at least one other method for user authentication.

ref: https://kubernetes.io/docs/admin/authentication/#authentication-strategies

**Comment by simoami** [comment]
I understand it means passing `--basic-auth-file=/accounts.csv` to the kube-apiserver command but where do I do that in the context of `kube-aws`?

**Comment by gianrubio** [comment]
You can edit https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L901 add your arguments and recompile your code again. 

If you already rendered the template you can just change  ./core/controlplane/config/templates/cloud-config-controller and update your stack

**Comment by simoami** [comment]
@gianrubio before I try that again. how do I upload accounts.csv? just place it in credentials folder and expect that it will be uploaded? or create one inline:
```
path: /etc/kubernetes/pki/accounts.csv
    content: |
      admin,admin,*
```

**Comment by gianrubio** [comment]
create one inline should works

**Comment by simoami** [comment]
@gianrubio My attempt at updating the stack resulted in a rollback. The edits passed validation but there was an error related to auto scaling group:

```
13:39:42 UTC-0500	UPDATE_FAILED	AWS::AutoScaling::AutoScalingGroup	Controllers	MinInstancesInService must be less than the autoscaling group's MaxSize
Physical ID:hipsync-cluster-Controlplane-166YHY3B1T38Q-Controllers-S0RUTSX1MQ1B
```

**Comment by simoami** [comment]
The update error is fixed by explicitly setting `rollingUpdateMinInstancesInService` in cluster.yaml to one count less than `maxSize` under `controller:`

**Comment by gianrubio** [comment]
this error  is related to #325, I'll work on this ASAP

**Comment by simoami** [comment]
@gianrubio since I changed the config, the controller is not coming up properly. I ssh'ed into the controller instance and printed the logs:

```
cat /var/log/containers/kube-apiserver-ip-10-0-0-145.ec2.internal_kube-system_kube-apiserver-f07199cceba3e6420071d974e5b4686d0f41b7093152392061a1188402ff9d18.log
{"log":"I0226 21:17:54.038062       1 config.go:527] Will report 10.0.0.145 as public IP address.\n","stream":"stderr","time":"2017-02-26T21:17:54.038435982Z"}
{"log":"I0226 21:17:54.038152       1 aws.go:749] Building AWS cloudprovider\n","stream":"stderr","time":"2017-02-26T21:17:54.038475322Z"}
{"log":"I0226 21:17:54.038172       1 aws.go:703] Zone not specified in configuration file; querying AWS metadata service\n","stream":"stderr","time":"2017-02-26T21:17:54.038483364Z"}
{"log":"I0226 21:17:54.296020       1 aws.go:836] AWS cloud filtering on tags: map[KubernetesCluster:hipsync-cluster]\n","stream":"stderr","time":"2017-02-26T21:17:54.296462695Z"}
{"log":"F0226 21:17:54.297975       1 server.go:244] Invalid Authentication Config: open /etc/kubernetes/pki/accounts.csv: no such file or directory\n","stream":"stderr","time":"2017-02-26T21:17:54.298329902Z"}
```

It complains that the file doesn't exist, but the file is there:
```
$ ls -l /etc/kubernetes/pki/accounts.csv
-rw-r--r--. 1 root root 22 Feb 26 21:10 /etc/kubernetes/pki/accounts.csv
$ cat /etc/kubernetes/pki/accounts.csv
admin,admin,1000
```

I wonder if the apiserver launches before? I added the creds file under `write_files:` [line 332](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L332)

**Comment by gianrubio** [comment]
You forgot to  mount the volume for this directory, remember you are running the apiserver as a pod.
https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L946-L959

**Comment by simoami** [comment]
Thanks @gianrubio, it worked! It would be nice to have this feature configurable in `cluster.yaml`.

Should someone have similar needs, here are the steps:

1. After running `kube-aws render stack`, open `./user_data/cloud-config-controller` for editing.

2. Under `write_files:` [line 332](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L332), insert the following but make sure you change the password to your own. you can also insert multiple account rows in there if you want to give access to other users:
```
  - path: /etc/kubernetes/pki/accounts.csv
    content: |
      Pa$$w0rd,admin,1000
```

3. Under `- apiserver` [line 901](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L901), insert the following:
```
- --basic-auth-file=/etc/kubernetes/pki/accounts.csv
```
4. Under `volumeMounts:` [line: 945](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L945), add volume mount:
```
          - mountPath: /etc/kubernetes/pki
            name: basic-auth-kubernetes
            readOnly: true 
```
           
5. Under `volumes:`[line: 957](https://github.com/coreos/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L957), add a volume:
```
        - hostPath: 
            path: /etc/kubernetes/pki
          name: basic-auth-kubernetes
```
6. validate your stack `kube-aws validate --s3-uri s3://<bucket>/<optional-path>`

7. If all is ok, run `kube-aws update --s3-uri s3://<bucket>/<optional-path>`

**Comment by erickfaustino** [comment]
@simoami, thanks you helped me a lot.

+1 to support basic auth on dashboard configurable by cluster.yaml
